app: vjepa
data:
  batch_size: 128
  crop_size: 224
  dataset_fpcs:
  - 16
  dataset_type: VideoDataset
  datasets:
  - /lab-share/Cardio-Mayourian-e2/Public/Echo_JEPA/avi_manifest_outside.csv
  datasets_weights:
  - 1.0
  fps: 8
  num_workers: 8
  patch_size: 16
  persistent_workers: true
  pin_mem: true
  tubelet_size: 2
data_aug:
  auto_augment: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.9
  - 1.1
  random_resize_scale:
  - 0.5
  - 1.0
  reprob: 0.0
federated:
  local_steps: 3
  mode: 1
  server: localhost:8080
  sync_momentum: 0.998
folder: /lab-share/Cardio-Mayourian-e2/Public/Echo_JEPA/checkpoints/fl/mode1_v5b/external
loss:
  loss_exp: 1.0
mask:
- aspect_ratio:
  - 0.75
  - 1.5
  full_complement: false
  max_keep: null
  max_temporal_keep: 1.0
  num_blocks: 8
  spatial_scale:
  - 0.15
  - 0.15
  temporal_scale:
  - 1.0
  - 1.0
- aspect_ratio:
  - 0.75
  - 1.5
  full_complement: false
  max_keep: null
  max_temporal_keep: 1.0
  num_blocks: 2
  spatial_scale:
  - 0.7
  - 0.7
  temporal_scale:
  - 1.0
  - 1.0
meta:
  dtype: bfloat16
  eval_freq: 100
  load_checkpoint: true
  read_checkpoint: /lab-share/Cardio-Mayourian-e2/Public/Echo_JEPA/checkpoints/fl/mode1_v5/external/round720.pt
  save_every_freq: 2
  seed: 234
  use_sdpa: true
model:
  model_name: vit_large
  num_mask_tokens: 10
  pred_depth: 12
  pred_embed_dim: 384
  pred_num_heads: 12
  uniform_power: true
  use_activation_checkpointing: true
  use_mask_tokens: true
  use_rope: true
  zero_init_mask_tokens: true
optimization:
  anneal_ckpt: /lab-share/Cardio-Mayourian-e2/Public/Echo_JEPA/checkpoints/vitl_vjepa2.pt
  ema:
  - 0.99925
  - 0.99925
  epochs: 240
  final_lr: 2.1875e-05
  final_weight_decay: 0.04
  force_load_pretrain: true
  ipe: 300
  ipe_scale: 1.25
  is_anneal: false
  lr: 2.1875e-05
  start_lr: 4.1625e-06
  warmup: 40
  weight_decay: 0.04
